version: '3.8'

services:
  flutter:
    build: .
    container_name: flutter_dev
    volumes:
      - ./mon-projet:/app           # Monte votre projet local dans le conteneur
      - flutter_pub_cache:/root/.pub-cache   # Partager le cache Flutter pour gagner de l'espace
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"    # Port pour le web debugging
      - "35000:35000"  # Port pour le hot reload
    command: /bin/bash

volumes:
  flutter_pub_cache:
