// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiFxE7UrWDZ15v9IIskvAJQNRQw-jAEAQ',
    appId: '1:146732852954:web:419b0ada7ff9a0d13c27e3',
    messagingSenderId: '146732852954',
    projectId: 'atelier4guedad-mohssine-iir5-3',
    authDomain: 'atelier4guedad-mohssine-iir5-3.firebaseapp.com',
    storageBucket: 'atelier4guedad-mohssine-iir5-3.firebasestorage.app',
    measurementId: 'G-CWZ1WLWHKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBepYXlviAzKKbXiMmygl_6B2J-KnthkRA',
    appId: '1:146732852954:android:9d9181e258b975693c27e3',
    messagingSenderId: '146732852954',
    projectId: 'atelier4guedad-mohssine-iir5-3',
    storageBucket: 'atelier4guedad-mohssine-iir5-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw9ojMkj7pm0B55oa_1xm4B-YadIaARWA',
    appId: '1:146732852954:ios:9847adbbeafc9a913c27e3',
    messagingSenderId: '146732852954',
    projectId: 'atelier4guedad-mohssine-iir5-3',
    storageBucket: 'atelier4guedad-mohssine-iir5-3.firebasestorage.app',
    iosBundleId: 'com.example.tpFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw9ojMkj7pm0B55oa_1xm4B-YadIaARWA',
    appId: '1:146732852954:ios:9847adbbeafc9a913c27e3',
    messagingSenderId: '146732852954',
    projectId: 'atelier4guedad-mohssine-iir5-3',
    storageBucket: 'atelier4guedad-mohssine-iir5-3.firebasestorage.app',
    iosBundleId: 'com.example.tpFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiFxE7UrWDZ15v9IIskvAJQNRQw-jAEAQ',
    appId: '1:146732852954:web:f584b773fbc4e3993c27e3',
    messagingSenderId: '146732852954',
    projectId: 'atelier4guedad-mohssine-iir5-3',
    authDomain: 'atelier4guedad-mohssine-iir5-3.firebaseapp.com',
    storageBucket: 'atelier4guedad-mohssine-iir5-3.firebasestorage.app',
    measurementId: 'G-XWPR0SED4E',
  );
}
